name : CICD
on: 
 workflow_dispatch:
  inputs:
    enviroment:
      description: This is the env where this workflow run
      default: 'dev'
      required: true
      type: choice
      options:
         - dev
         - prod
         - staging    

jobs:
  code:
   runs-on: ubuntu-latest
   steps:
      - name: checkout code
        run: echo "Code clone form git"
  build:
   needs: [code] 
   runs-on: ubuntu-latest
   steps:
        - name: Build docker container
          run: echo "Testting the container"
  test:
    needs: [build,code]
    runs-on: ubuntu-latest
    steps:
      - name: Test The Container
        run: echo "Testing the container"
  deploy:
    if: inputs.enviroment == 'dev'
    needs: [build,code,test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy onserver
        run: echo "Docker Compase deployed the app"

  
  
   
    
    
