# this is workflow name
name: Hello Workflow

# runs on trigger 
on:
 push: 
  branches: [main]
  paths: 
    - '**.html'
    - 'hello.yml'
# these are the jobs inside workflow
jobs:
# this is name of the job
  greet:
  # this is git hub runner 
    runs-on: ubuntu-latest
    steps:
      - name: say hello to users
        run: echo "Hello Dosto"
      - name: say hello to user name
        run: echo "Hello $USER"
        
  details:
   runs-on:  ubuntu-latest 
   steps:
    - name: version of python,docker,etc
      run: docker --version && python --version
